# Generated by Django 2.0 on 2018-12-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mb', 'Placas base'), ('cp', 'CPUs'), ('hd', 'Discos Duros'), ('gc', 'Tarjetas gráficas'), ('ra', 'RAM'), ('la', 'Portátiles'), ('gl', 'Portátiles Gaming')], default='la', max_length=2),
        ),
    ]
