# Generated by Django 2.0 on 2019-01-19 15:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.AlterField(
            model_name='price',
            name='currentPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='originalPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mb', 'Placas base'), ('cp', 'CPUs'), ('hd', 'Discos Duros'), ('gc', 'Tarjetas gráficas'), ('ra', 'RAM'), ('la', 'Portátiles'), ('gl', 'Portátiles Gaming'), ('sm', 'Smartphones'), ('tv', 'Televisores')], default='la', max_length=2),
        ),
        migrations.AddField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
