# Generated by Django 2.0 on 2018-12-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181231_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='currentPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='originalPrice',
            field=models.FloatField(),
        ),
    ]
