# Generated by Django 2.0 on 2019-01-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181231_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mb', 'Placas base'), ('cp', 'CPUs'), ('hd', 'Discos Duros'), ('gc', 'Tarjetas gráficas'), ('ra', 'RAM'), ('la', 'Portátiles'), ('gl', 'Portátiles Gaming'), ('sm', 'Smartphones'), ('tv', 'Televisores')], default='la', max_length=2),
        ),
    ]
