# Generated by Django 2.0 on 2019-01-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='currentPrice',
            new_name='rating',
        ),
    ]
