# Generated by Django 2.0 on 2019-01-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190119_1204'),
        ('products', '0004_auto_20190118_2038'),
    ]

    operations = [
    ]
